version: '3'

services:
  reverse-proxy:
    image: reverse:latest
    container_name: reverse-proxy
    ports:
    - '80:80'
    networks:
      - backend
  web:
    build: ./web
    container_name: web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/web_django
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
    networks:
      - backend

networks:
  backend: null
